### ISSUE TITLE
Start YAML output with `---`

### ISSUE THREAD

**Issue by dsiebel** [k14s/kbld#16]
Background:
I use `kbld` to dynamically replace docker `image:tag` notations with `image:digest` before applying the manifests in a pipeline like this:

`custom-script-to-render-multiple-helm-charts | kbld -f - | kubectl apply -f -`

According to the [YAML spec](https://yaml.org/spec/1.2/spec.html#id2760395) a YAML document _may_ start with `---`. 
Adding `---` on the top of every YAML file (even empty ones) has proven specifically useful when concatenating the output of tools like `kubectl`, `helm template` and also `kbld` into a single file and is hence somewhat considered a best practice (at least in my filter-bubble).

`kbld` does not (yet) add `---` on top of its output by default and does not have an option to enable it either. It would be really helpful to have it.

I am happy to provide a PR if you pointed me in the right direction.

**Comment by cppforlife** [comment]
available in https://github.com/k14s/kbld/releases/tag/v0.12.0
