### ISSUE TITLE
Support registry to registry direct relocation

### ISSUE THREAD

**Issue by ewrenn8** [k14s/kbld#28]
- [ ] Introduce a command `kbld relocate -f install.yml --repository my.internal.reg` that will skip writing the image layers to disk and will stream them directly to the new repository.

- [ ] kbld relocate supports the --lock-output flag to maintain a mapping from manifest image locations to current image locations. See [packaging docs](https://github.com/k14s/kbld/blob/master/docs/packaging.md) for more details on the workflow

```
# new lock file containes manifest images => digest references in new repo
kbld relocate -f images.lock --repository <dst registry> --lock-output relocated-images.lock
kbld relocate -f images.lock -r <dst registry> --lock-output relocated-images.lock 
```

**Comment by cppforlife** [comment]
https://github.com/k14s/kbld/releases/tag/v0.23.0 includes this feature.
