### ISSUE TITLE
Introduce lock file interface

### ISSUE THREAD

**Issue by ewrenn8** [k14s/kbld#29]
kbld relocation commands should use lock files as an interface for relocating images. A lock file will consist of the original image reference from the configuration manifests (image: nginx) along with the current location of the image (my.internal.registry/app1@<digest>). The workflow will look like:
```
kbld -f manifest.yml --lock-output images.lock // lock file contains manifest images => digest references in source registry
kbld pkg -f images.lock -o images.tar
kbld unpkg -f images.lock --input images.tar --repository <new repo> --lock-output relocated-images.lock // new lock file containes manifest images => digest references in new repo
```
And for all in one relocation:
```
kbld -f manifest.yml --lock-output images.lock // lock file contains manifest images => digest references in source registry
kbld relocate -f images.lock --src <extranl registry> --dst <internal registry> --lock-output relocated-images.lock // new lock file containes manifest images => digest references in new repo
```
See [packaging docs](https://github.com/k14s/kbld/blob/master/docs/packaging.md) for more details on the workflow

- [ ] pkg/unpkg flow
- [ ] relocate flow (relies on #28)

**Comment by cppforlife** [comment]
instead of

```
kbld relocate -f images.lock --src <extranl registry> --dst <internal registry> --lock-output relocated-images.lock // new lock file containes manifest images => digest references in new repo
```

i think following works out better:

```bash
# new lock file containes manifest images => digest references in new repo
kbld relocate -f images.lock --repository <dst registry> --lock-output relocated-images.lock
kbld relocate -f images.lock -r <dst registry> --lock-output relocated-images.lock
```

(we do not need source registry, since we have image refs from images.lock; -r is also consistent with unpkg command)

**Comment by ewrenn8** [comment]
Closing in favor of doing this as part of implementing relocate command
